import 'dart:convert';
import 'package:http/http.dart' as http;
import '../models/medicine_schedule.dart';

class Esp32Service {
  String _boxIp = '';
  bool _isConnected = false;
  DateTime? _lastSync;

  String get boxIp => _boxIp;
  bool get isConnected => _isConnected;
  DateTime? get lastSync => _lastSync;

  void setBoxIp(String ip) {
    _boxIp = ip;
  }

  Future<bool> testConnection() async {
    if (_boxIp.isEmpty) return false;

    try {
      final response = await http
          .get(Uri.parse('http://$_boxIp/api/status'))
          .timeout(const Duration(seconds: 5));

      _isConnected = response.statusCode == 200;
      return _isConnected;
    } catch (e) {
      _isConnected = false;
      return false;
    }
  }

  Future<Map<String, dynamic>?> getBoxStatus() async {
    if (_boxIp.isEmpty || !_isConnected) return null;

    try {
      final response = await http
          .get(Uri.parse('http://$_boxIp/api/status'))
          .timeout(const Duration(seconds: 5));

      if (response.statusCode == 200) {
        return jsonDecode(response.body) as Map<String, dynamic>;
      }
      return null;
    } catch (e) {
      _isConnected = false;
      return null;
    }
  }

  Future<bool> syncSchedule(List<MedicineSchedule> schedules) async {
    if (_boxIp.isEmpty) return false;

    try {
      final payload = {
        'schedules': schedules.map((s) => s.toEsp32Json()).toList(),
        'timestamp': DateTime.now().toIso8601String(),
      };

      final response = await http
          .post(
            Uri.parse('http://$_boxIp/api/schedule'),
            headers: {'Content-Type': 'application/json'},
            body: jsonEncode(payload),
          )
          .timeout(const Duration(seconds: 10));

      if (response.statusCode == 200) {
        _lastSync = DateTime.now();
        return true;
      }
      return false;
    } catch (e) {
      _isConnected = false;
      return false;
    }
  }

  Future<bool> markDoseAsTaken(String compartment) async {
    if (_boxIp.isEmpty || !_isConnected) return false;

    try {
      final response = await http
          .post(
            Uri.parse('http://$_boxIp/api/dose-taken'),
            headers: {'Content-Type': 'application/json'},
            body: jsonEncode({'compartment': compartment}),
          )
          .timeout(const Duration(seconds: 5));

      return response.statusCode == 200;
    } catch (e) {
      return false;
    }
  }

  Future<bool> openCompartment(String compartment) async {
    if (_boxIp.isEmpty || !_isConnected) return false;

    try {
      final response = await http
          .post(
            Uri.parse('http://$_boxIp/api/open'),
            headers: {'Content-Type': 'application/json'},
            body: jsonEncode({'compartment': compartment}),
          )
          .timeout(const Duration(seconds: 5));

      return response.statusCode == 200;
    } catch (e) {
      return false;
    }
  }

  Future<bool> resetBox() async {
    if (_boxIp.isEmpty || !_isConnected) return false;

    try {
      final response = await http
          .post(Uri.parse('http://$_boxIp/api/reset'))
          .timeout(const Duration(seconds: 10));

      if (response.statusCode == 200) {
        _lastSync = null;
        return true;
      }
      return false;
    } catch (e) {
      return false;
    }
  }

  String generateEsp32ArduinoCode(List<MedicineSchedule> schedules, String boxId) {
    return '''
/*
 * Care Cube - Smart Medicine Box (ESP32)
 * Generated by Care Cube App
 * ==========================================================
 * HARDWARE:
 *   - 2x VL53L0X Time-of-Flight sensors (I2C, 0x30, 0x31)
 *   - DS3231 RTC for time-based reminders
 *   - DHT22 temperature & humidity sensor
 *   - 16x4 I2C LCD display
 *   - Buzzer (GPIO 25) + 2x LEDs (GPIO 26, 27)
 *
 * MQTT TOPICS:
 *   Status:   care_cube/$boxId/status
 *   Commands: care_cube/$boxId/commands
 *
 * REQUIRED LIBRARIES (Arduino IDE -> Library Manager):
 *   - Adafruit VL53L0X
 *   - LiquidCrystal I2C (Frank de Brabander)
 *   - DHT sensor library (Adafruit)
 *   - RTClib (Adafruit)
 *   - PubSubClient (Nick O'Leary)
 *   - ArduinoJson
 * ==========================================================
 */

#include <Wire.h>
#include <RTClib.h>
#include <LiquidCrystal_I2C.h>
#include <DHT.h>
#include <VL53L0X.h>
#include <WiFi.h>
#include <WebServer.h>
#include <PubSubClient.h>
#include <Preferences.h>
#include <ArduinoJson.h>

const char* WIFI_SSID     = "YOUR_WIFI_SSID";
const char* WIFI_PASSWORD = "YOUR_WIFI_PASSWORD";
const char* BOX_ID        = "$boxId";
const char* MQTT_SERVER    = "broker.hivemq.com";
const int   MQTT_PORT      = 1883;

#define SDA_PIN 21
#define SCL_PIN 22
#define DHTPIN 4
#define DHTTYPE DHT22
#define BUZZER 25
#define LED1 26
#define LED2 27
#define XSHUT1 18
#define XSHUT2 19

RTC_DS3231 rtc;
LiquidCrystal_I2C lcd(0x27, 16, 4);
DHT dht(DHTPIN, DHTTYPE);
VL53L0X sensor1;
VL53L0X sensor2;

WiFiClient   wifiClient;
PubSubClient  mqtt(wifiClient);
WebServer     setupServer(80);
Preferences   prefs;

int s1Hour = 8, s1Minute = 0;
int s2Hour = 14, s2Minute = 0;
const int DISTANCE_LIMIT = 70;
const unsigned long MEDICINE_DISPLAY_TIME = 2UL * 60UL * 1000UL;

bool s1ReminderDone = false, s2ReminderDone = false;
bool s1ReminderActive = false, s2ReminderActive = false;
bool s1MedicineTaken = false, s2MedicineTaken = false;
int activeSensor = 0;
bool medicineTakenDisplay = false;
unsigned long medicineTakenStartTime = 0;
unsigned long lastPublish = 0;
bool setupMode = false;
bool prevPresent1 = false, prevPresent2 = false;

String getJsonValue(String json, String key) {
  String search = String("\\\"") + key + "\\\"";
  int pos = json.indexOf(search);
  if (pos == -1) return "";
  pos += search.length();
  while (pos < (int)json.length() && (json[pos] == ' ' || json[pos] == ':' || json[pos] == '"')) pos++;
  String value;
  while (pos < (int)json.length() && json[pos] != '"' && json[pos] != '}' && json[pos] != ',') {
    value += json[pos]; pos++;
  }
  return value;
}

int getDistance(VL53L0X &sensor) {
  long total = 0; int valid = 0;
  for (int i = 0; i < 5; i++) {
    int d = sensor.readRangeContinuousMillimeters();
    if (!sensor.timeoutOccurred()) { total += d; valid++; }
    delay(20);
  }
  return (valid == 0) ? 9999 : total / valid;
}

void showNormalScreen(DateTime now, float temp, float hum) {
  lcd.clear();
  lcd.setCursor(0, 0); lcd.print("Time: ");
  if (now.hour() < 10) lcd.print("0"); lcd.print(now.hour()); lcd.print(":");
  if (now.minute() < 10) lcd.print("0"); lcd.print(now.minute());
  lcd.setCursor(0, 1); lcd.print("Tmp:"); lcd.print(temp, 1); lcd.print("C Hum:"); lcd.print(hum, 0); lcd.print("%");
  lcd.setCursor(0, 2); lcd.print(BOX_ID);
  lcd.setCursor(0, 3);
  if (s1MedicineTaken || s2MedicineTaken) lcd.print("MEDICINE TAKEN");
  else lcd.print("SYSTEM READY");
}

void showMedicineScreen(int sn, int dist) {
  lcd.clear();
  lcd.setCursor(0, 0); lcd.print("!! REMINDER !!");
  lcd.setCursor(0, 1); lcd.print("CUP "); lcd.print(sn);
  lcd.print(dist <= DISTANCE_LIMIT ? ": PLEASE TAKE" : ": TAKEN");
}

void showMedicineTakenScreen(int sn) {
  lcd.clear();
  lcd.setCursor(0, 1); lcd.print("CUP "); lcd.print(sn);
  lcd.setCursor(0, 2); lcd.print("TAKEN SUCCESSFULLY");
}

bool connectWiFi(String ssid, String pass) {
  if (ssid.isEmpty() || ssid == "YOUR_WIFI_SSID") return false;
  WiFi.mode(WIFI_STA); WiFi.begin(ssid.c_str(), pass.c_str());
  unsigned long start = millis();
  while (WiFi.status() != WL_CONNECTED && millis() - start < 20000) delay(500);
  return WiFi.status() == WL_CONNECTED;
}

void startSetupMode() {
  setupMode = true;
  WiFi.mode(WIFI_AP); WiFi.softAP("CareCube_Setup");
  setupServer.on("/setup", HTTP_POST, []() {
    String body = setupServer.arg("plain");
    String ssid = getJsonValue(body, "ssid");
    String pass = getJsonValue(body, "pass");
    setupServer.send(200, "text/plain", "OK");
    if (ssid.isEmpty()) return;
    prefs.putString("ssid", ssid); prefs.putString("pass", pass); prefs.end();
    if (connectWiFi(ssid, pass)) { delay(500); ESP.restart(); }
    else { WiFi.mode(WIFI_AP); WiFi.softAP("CareCube_Setup"); }
  });
  setupServer.begin();
  lcd.clear(); lcd.setCursor(0, 0); lcd.print("SETUP MODE"); lcd.setCursor(0, 1); lcd.print("CONNECT TO WIFI");
}

String getStatusTopic() { return String("care_cube/") + String(BOX_ID) + "/status"; }
String getCommandTopic() { return String("care_cube/") + String(BOX_ID) + "/commands"; }
String getAlertTopic() { return String("medicinebox/notifications"); }

bool mqttConnect() {
  if (mqtt.connected()) return true;
  String clientId = String("care_cube_") + String(BOX_ID) + "_" + String((uint32_t)ESP.getEfuseMac(), HEX);
  if (mqtt.connect(clientId.c_str())) {
    mqtt.subscribe(getCommandTopic().c_str());
    lastPublish = 0;
    return true;
  }
  return false;
}

void publishAlert(const char* msg) { if (mqttConnect()) mqtt.publish(getAlertTopic().c_str(), msg); }

void publishStatus(int d1, int d2, bool p1, bool p2, int count, float temp, float hum, String doseTaken) {
  String p = String("{\\\"box_id\\\":\\\"") + String(BOX_ID) + "\\\","
    "\\\"sensor1_distance\\":" + String(d1) + ","
    "\\\"sensor2_distance\\":" + String(d2) + ","
    "\\\"compartment1_present\\":" + String(p1 ? "true" : "false") + ","
    "\\\"compartment2_present\\":" + String(p2 ? "true" : "false") + ","
    "\\\"temperature\\":" + String(isnan(temp) ? 0 : temp, 1) + ","
    "\\\"humidity\\":" + String(isnan(hum) ? 0 : hum, 1) + ","
    "\\\"medicine_count\\":" + String(count) + ","
    "\\\"total_compartments\\\":2";
  if (doseTaken.length() > 0) p += ",\\\"dose_taken\\\":\\\"" + doseTaken + "\\\"";
  p += "}";
  if (mqttConnect()) mqtt.publish(getStatusTopic().c_str(), p.c_str());
}

void mqttCallback(char* topic, byte* payload, unsigned int length) {
  String message; for (unsigned int i = 0; i < length; i++) message += (char)payload[i];
  String cmd = getJsonValue(message, "command");
  if (cmd == "set_schedule") {
    int sensor = getJsonValue(message, "sensor").toInt();
    int h = getJsonValue(message, "hour").toInt();
    int m = getJsonValue(message, "minute").toInt();
    if (sensor == 1) { s1Hour = h; s1Minute = m; s1ReminderDone = false; }
    else if (sensor == 2) { s2Hour = h; s2Minute = m; s2ReminderDone = false; }
    publishAlert("CONFIRMED: Schedule updated");
  } else if (cmd == "open") {
    String comp = getJsonValue(message, "compartment");
    lcd.clear(); lcd.setCursor(0, 0); lcd.print("OPENING"); lcd.setCursor(0, 1); lcd.print(comp);
    delay(2000);
  }
}

void setup() {
  Serial.begin(115200);
  Wire.begin(SDA_PIN, SCL_PIN);
  lcd.init(); lcd.backlight();
  lcd.clear(); lcd.setCursor(0, 0); lcd.print("MEDICINE BOX"); lcd.setCursor(0, 1); lcd.print("Starting...");
  dht.begin();
  pinMode(BUZZER, OUTPUT); digitalWrite(BUZZER, LOW);
  pinMode(LED1, OUTPUT); pinMode(LED2, OUTPUT); digitalWrite(LED1, LOW); digitalWrite(LED2, LOW);
  if (!rtc.begin()) { lcd.clear(); lcd.print("RTC ERROR"); while(1); }

  pinMode(XSHUT1, OUTPUT); pinMode(XSHUT2, OUTPUT);
  digitalWrite(XSHUT1, LOW); digitalWrite(XSHUT2, LOW); delay(100);
  digitalWrite(XSHUT1, HIGH); delay(100);
  sensor1.setTimeout(500); if (!sensor1.init()) { lcd.clear(); lcd.print("S1 FAIL"); while(1); }
  sensor1.setAddress(0x30); sensor1.startContinuous();
  digitalWrite(XSHUT2, HIGH); delay(100);
  sensor2.setTimeout(500); if (!sensor2.init()) { lcd.clear(); lcd.print("S2 FAIL"); while(1); }
  sensor2.setAddress(0x31); sensor2.startContinuous();

  prefs.begin("carecube", false);
  String ssid = prefs.getString("ssid", String(WIFI_SSID));
  String pass = prefs.getString("pass", String(WIFI_PASSWORD));
  if (connectWiFi(ssid, pass)) { mqtt.setServer(MQTT_SERVER, MQTT_PORT); mqtt.setCallback(mqttCallback); mqttConnect(); publishAlert("CARE CUBE: Online"); }
  else startSetupMode();

  lcd.clear(); lcd.setCursor(0, 0); lcd.print("MEDICINE BOX"); lcd.setCursor(0, 1); lcd.print("SYSTEM READY");
  delay(2000); lcd.clear();
}

void loop() {
  if (WiFi.status() == WL_CONNECTED) {
    if (setupMode) { setupMode = false; WiFi.mode(WIFI_STA); }
    if (!mqtt.connected()) mqttConnect();
    mqtt.loop();
  } else {
    if (!setupMode) startSetupMode();
    setupServer.handleClient(); delay(10); return;
  }

  DateTime now = rtc.now();
  float temp = dht.readTemperature();
  float hum = dht.readHumidity();
  int d1 = getDistance(sensor1), d2 = getDistance(sensor2);
  bool p1 = (d1 >= 0 && d1 <= DISTANCE_LIMIT), p2 = (d2 >= 0 && d2 <= DISTANCE_LIMIT);
  int mc = (p1 ? 1 : 0) + (p2 ? 1 : 0);

  String doseTaken = "";
  if (prevPresent1 && !p1) doseTaken = "Cup 1";
  if (prevPresent2 && !p2) doseTaken = doseTaken.length() > 0 ? doseTaken : "Cup 2";
  prevPresent1 = p1; prevPresent2 = p2;

  unsigned long nowMs = millis();
  if (nowMs - lastPublish >= 3000) { lastPublish = nowMs; publishStatus(d1, d2, p1, p2, mc, temp, hum, doseTaken); }

  if (now.hour() == s1Hour && now.minute() == s1Minute && !s1ReminderDone && !s1ReminderActive && !s2ReminderActive && !medicineTakenDisplay) {
    s1ReminderActive = true; activeSensor = 1; s1MedicineTaken = false;
    digitalWrite(BUZZER, HIGH); digitalWrite(LED1, HIGH); digitalWrite(LED2, LOW);
    publishAlert("REMINDER: Take Cup 1 medicine NOW!");
  }
  if (now.hour() == s2Hour && now.minute() == s2Minute && !s2ReminderDone && !s2ReminderActive && !s1ReminderActive && !medicineTakenDisplay) {
    s2ReminderActive = true; activeSensor = 2; s2MedicineTaken = false;
    digitalWrite(BUZZER, HIGH); digitalWrite(LED2, HIGH); digitalWrite(LED1, LOW);
    publishAlert("REMINDER: Take Cup 2 medicine NOW!");
  }

  if (medicineTakenDisplay) {
    showMedicineTakenScreen(activeSensor);
    if (millis() - medicineTakenStartTime >= MEDICINE_DISPLAY_TIME) { medicineTakenDisplay = false; activeSensor = 0; lcd.clear(); }
  } else if (s1ReminderActive) {
    showMedicineScreen(1, d1);
    if (d1 > DISTANCE_LIMIT) {
      s1ReminderActive = false; s1ReminderDone = true; s1MedicineTaken = true;
      digitalWrite(BUZZER, LOW); digitalWrite(LED1, LOW); digitalWrite(LED2, LOW);
      medicineTakenDisplay = true; activeSensor = 1; medicineTakenStartTime = millis();
      publishAlert("CONFIRMED: Cup 1 medicine TAKEN");
    } else { digitalWrite(BUZZER, HIGH); digitalWrite(LED1, HIGH); digitalWrite(LED2, LOW); }
  } else if (s2ReminderActive) {
    showMedicineScreen(2, d2);
    if (d2 > DISTANCE_LIMIT) {
      s2ReminderActive = false; s2ReminderDone = true; s2MedicineTaken = true;
      digitalWrite(BUZZER, LOW); digitalWrite(LED2, LOW); digitalWrite(LED1, LOW);
      medicineTakenDisplay = true; activeSensor = 2; medicineTakenStartTime = millis();
      publishAlert("CONFIRMED: Cup 2 medicine TAKEN");
    } else { digitalWrite(BUZZER, HIGH); digitalWrite(LED2, HIGH); digitalWrite(LED1, LOW); }
  } else {
    showNormalScreen(now, temp, hum); digitalWrite(LED1, LOW); digitalWrite(LED2, LOW);
  }

  if (now.hour() == 0 && now.minute() == 1) { s1ReminderDone = false; s2ReminderDone = false; }
  delay(500);
}
''';
  }
}
